version: "3.4"

services:

  localstack:
    container_name: aws_sqs
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_OUTPUT=json
      - SERVICES=sqs
    volumes:
      - ./local/aws/sqs-configuration.sh:/etc/localstack/init/ready.d/init-aws.sh

  flyway:
    image: flyway/flyway:7.14-alpine
    container_name: digital-account-flyway
    command: -url=jdbc:postgresql://postgres:5432/digital-account-service -schemas=digital_account_service -user=digital-account-service-migration -password=digital-account-service-migration migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: digital-account-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "mM@md38d23"
    volumes:
      - ./local/setup-postgresql-databases.sh:/docker-entrypoint-initdb.d/setup-postgresql-databases.sh

  fake-service:
    image: mockoon/cli:1.5.1
    container_name: fake-service
    ports:
      - "3001:3001"
    command: -d /data -i 0 -p 3001
    volumes:
      - ./local/mockoon/data.json:/data

  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
     - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./loadtest/dashboards/dashboards:/var/lib/grafana/dashboards
      - ./loadtest/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./loadtest/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./loadtest/scripts:/scripts
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  k6:
  grafana: