version: "3.4"

services:

  flyway:
    image: flyway/flyway:7.14-alpine
    container_name: digital-account-flyway
    command: -url=jdbc:postgresql://postgres:5432/digital-account-service -schemas=digital_account_service -user=digital-account-service-migration -password=digital-account-service-migration migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres
    networks:
      - digital-account-network

  postgres:
    image: postgres
    container_name: digital-account-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "mM@md38d23"
    volumes:
      - ./local/setup-postgresql-databases.sh:/docker-entrypoint-initdb.d/setup-postgresql-databases.sh
    networks:
      - digital-account-network

networks:
  digital-account-network:
    driver: bridge
    name: digital-account-network