server:
  port: 8055

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digital-account-service?TimeZone=UTC,schema=digital_account_service
    username: digital-account-service-app
    password: digital-account-service-app
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    credentials:
      access-key: dummy
      secret-key: dummy
      useDefaultAwsCredentialsChain: true
    profile: localstack
    sqs:
      end-point:
        uri: http://localhost:4566/000000000000/process-queue
        queue-name: process-queue
    s3:
      endpoint:
        uri: http://s3.localhost.localstack.cloud:4566/
      bucket-name: process-storage
      file-name: example.txt


aws:
  secretsmanager:
    enabled: true
    endpoint: http://localhost:4566

logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

