
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digital-account-service?TimeZone=UTC,schema=digital_account_service
    username: digital-account-service-app
    password: digital-account-service-app
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
